config/routes.rb
SportMonkey::Application.routes.draw do  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :tournaments, :only => [:index, :show]

  get 'golfers/index/:alphabet' => 'golfers#list', :as => :list_golfers

  resources :golfers, only: [:index, :show]

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  root :to => 'pages#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/golfer.rb
class Golfer < ActiveRecord::Base
  has_many :results
  has_many :tournaments, :through => :results
  
  scope :initial, lambda {|alphabet| where("name LIKE ?", "#{alphabet}%") }
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :golfer
  
  validates :place, :winnings, :tournament_id, :golfer_id, presence: true
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :results
  has_many :golfers, :through => :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/golfers_controller.rb
class GolfersController < ApplicationController
  def list
    @title = "Golfers List"
    @golfers = Golfer.initial(params[:alphabet])
    
    render 'index'
  end
  
  # GET /golfers
  # GET /golfers.json
  def index
    @title = "Golfers"
    @golfers = Golfer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @golfers }
    end
  end

  # GET /golfers/1
  # GET /golfers/1.json
  def show
    @golfer = Golfer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @golfer }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "landing_page"
  
  def home
    @title = 'Welcome'
  end

  def contact
    @title = 'Contact'
  end

  def about
    @title = 'About'
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tournaments }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament = Tournament.find(params[:id])
    @result = Result.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: [@tournament, @tournament.results] }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/golfers_helper.rb
module GolfersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/golfers/index.html.haml
%h1 Golfers
|
- ('A'..'Z').each do |letter|
  =link_to letter, list_golfers_path(:alphabet => letter)
  |

%table
  %tr
    %th Name
    %th
    %th

  - @golfers.each do |golfer|
    %tr
      %td= link_to golfer.name, golfer

app/views/golfers/show.html.haml
-if notice
  %p#notice.alert-message.success= notice

%h1
  = @golfer.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "SportMonkey | #{@title}"
    = stylesheet_link_tag		 "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
	  
  %body(class="#{controller.controller_name}")
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{:data => {:toggle => "collapse", :target => ".nav-collapse"}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            
          =link_to "SportMonkey.ca", root_url, :class => "brand"
          
          .nav-collapse
            %ul.nav
              %li= link_to "Home", root_url , :class => "active"
              %li= link_to "Golfers", golfers_path
              %li= link_to "Tournaments", tournaments_path
              %li= link_to "About", "#about"
              %li= link_to "Contact", "#contact"
              
            %p.navbar-text.pull-right= "Logged in as #{link_to("username", "#")}"
          
    .container-fluid
      .span3
        .well.sidebar-nav
          %ul.nav.nav-list
            %li.nav-header Shortcuts
            %li.active= link_to "Active Link", "#"
            %li= link_to "Link", "#"
    
      .span9
        .content
          = yield
  
          %hr
  
          #footer
            %p &copy; SportMonkey.ca 2011

app/views/layouts/landing_page.html.haml
!!!
%html
  %head
    %title= "SportMonkey | #{@title}"
    = stylesheet_link_tag		 "application", "landing_page"
    = javascript_include_tag "application"
    = csrf_meta_tags
	  
  %body.landing_page
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{:data => {:toggle => "collapse", :target => ".nav-collapse"}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            
          = link_to "SportMonkey", root_url, :class => "brand"
          .nav-collapse
            %ul.nav
              %li= link_to "Home", root_url , :class => "active"
              %li=# link_to "About", :pages_about
              %li=# link_to "Contact", :pages_contact
          
    .container
      = yield
      
      %hr
      
      #footer
        %p &copy; SportMonkey.ca 2011

app/views/pages/about.html.haml
.hero-unit
  %h1 About
  %p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
.hero-unit
  %h1 Contact us
  %p You can reach us at #{mail_to "admin@sportmonkey.ca", "SportMonkey Admin", :encode => "javascript"}

app/views/pages/home.html.haml
.hero-unit
  %h1 SportMonkey!
  %p It's your lucky day. You've found us! Now get ready for the challenge.
  %p Do you want to put your sport's knowledge to the test and try to guess who are the best players of the season?
  %p Choose your favourite players, challenge your friends and let's see who gets the best results.
  %p=link_to "Check latest results", "https://docs.google.com/spreadsheet/ccc?key=0AhvCGr-ppdV3dDVWcm9EZ0pib2hiYUNnUEM3WmNwYnc", :id => 'latest-results', :class => "btn btn-primary btn-large"

app/views/results/_result.html.haml
%tr
  %td
    =result.place
  %td
    =link_to result.golfer.name, result.golfer
  %td
    =number_to_currency(result.winnings, precision: 0)

app/views/tournaments/_form.html.haml
= form_for @tournament do |f|
  -if @tournament.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tournament.errors.count, "error")} prohibited this tournament from being saved:"
      %ul
        - @tournament.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :course
    = f.text_field :course
  .field
    = f.label :end_date
    = f.date_select :end_date
  .actions
    = f.submit 'Save', :class => 'btn primary'

app/views/tournaments/index.html.haml
%h1 Listing tournaments

%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Course
      %th End Date
      
  %tbody
  - @tournaments.each do |tournament|
    %tr
      %td= link_to tournament.name, tournament
      %td= tournament.course
      %td= tournament.end_date

app/views/tournaments/show.html.haml
%p#notice= notice

%h1
  = @tournament.name
%p
  %b Course:
  = @tournament.course
%p
  %b End Date:
  = @tournament.end_date

%h2 Results

%table
  %thead
    %tr
      %th Place
      %th Golfer
      %th Winnings
  %tbody
  =render @tournament.results